[package]
name = "wunderbar"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
cocoa = "0.25.0"
core-graphics = "0.23.2"
libc = "0.2.155"
objc = "0.2.7"
